### ISSUE TITLE
`sl4j-api-2.0.11` throws `java.lang.NullPointerException` in Android build

### ISSUE THREAD

**Issue by georgepadayatti** [qos-ch/slf4j#401]
`sl4j-api-2.0.11` throws `java.lang.NullPointerException` during Android build. But works perfect in versions `2.0.9` and below.

**Comment by ceki** [comment]
@georgepadayatti Did you forget to provide a stack trace?

**Comment by vitalyster** [comment]
[This commit](https://github.com/qos-ch/slf4j/commit/db8cd90c10cda662db899e1f72644638013b7ec6) breaks Android <24 compatibility: java.util.function package used there is not present on older devices.

**Comment by ceki** [comment]
I cannot make sense of the stack stace provided vby @introfog which mentions jetified-slf4j-api-2.0.10.jar. I do not know what artifact that is.

As for the comment by @vitalyster, java.util.function package is required by the SLF4J's fluent API. 

In short, I would like to help but I am not familiar with android development.

**Comment by kaushal98** [comment]
I also faced this while upgrading to 2.0.16. Pasting relevant snippets from gradle build

```
Caused by: com.android.tools.r8.CompilationFailedException: Compilation failed to complete, origin: ~/jetified-slf4j-api-2.0.16.jar:org/slf4j/event/Level.class
	at Version.fakeStackEntry(Version_4.0.48.java:0)
```

```
Caused by: com.android.tools.r8.CompilationFailedException: Compilation failed to complete, origin: ~/jetified-slf4j-simple-2.0.16.jar:org/slf4j/simple/OutputChoice$OutputChoiceType.class
	at Version.fakeStackEntry(Version_4.0.48.java:0)
	at com.android.tools.r8.internal.vk.a(R8_4.0.48_320a4fe2564c68ad8fe4492fea65872bc8f51e21c4d46e3dbac43afcc38d90de:75)
	at com.android.tools.r8.internal.vk.a(R8_4.0.48_320a4fe2564c68ad8fe4492fea65872bc8f51e21c4d46e3dbac43afcc38d90de:28)
	at com.android.tools.r8.internal.vk.a(R8_4.0.48_320a4fe2564c68ad8fe4492fea65872bc8f51e21c4d46e3dbac43afcc38d90de:27)
	at com.android.tools.r8.internal.vk.b(R8_4.0.48_320a4fe2564c68ad8fe4492fea65872bc8f51e21c4d46e3dbac43afcc38d90de:2)
	at com.android.tools.r8.D8.run(R8_4.0.48_320a4fe2564c68ad8fe4492fea65872bc8f51e21c4d46e3dbac43afcc38d90de:11)
	at com.android.builder.dexing.D8DexArchiveBuilder.convert(D8DexArchiveBuilder.java:120)
	... 38 more
Caused by: java.lang.NullPointerException: Cannot invoke "String.length()" because "<parameter1>" is null
```

**Comment by JungHsuan** [comment]
> I also faced this while upgrading to 2.0.16. Pasting relevant snippets from gradle build
> 
> ```
> Caused by: com.android.tools.r8.CompilationFailedException: Compilation failed to complete, origin: ~/jetified-slf4j-api-2.0.16.jar:org/slf4j/event/Level.class
> 	at Version.fakeStackEntry(Version_4.0.48.java:0)
> 	at com.android.tools.r8.internal.vk.a(R8_4.0.48_320a4fe2564c68ad8fe4492fea65872bc8f51e21c4d46e3dbac43afcc38d90de:75)
> 	at com.android.tools.r8.internal.vk.a(R8_4.0.48_320a4fe2564c68ad8fe4492fea65872bc8f51e21c4d46e3dbac43afcc38d90de:28)
> 	at com.android.tools.r8.internal.vk.a(R8_4.0.48_320a4fe2564c68ad8fe4492fea65872bc8f51e21c4d46e3dbac43afcc38d90de:27)
> 	at com.android.tools.r8.internal.vk.b(R8_4.0.48_320a4fe2564c68ad8fe4492fea65872bc8f51e21c4d46e3dbac43afcc38d90de:2)
> 	at com.android.tools.r8.D8.run(R8_4.0.48_320a4fe2564c68ad8fe4492fea65872bc8f51e21c4d46e3dbac43afcc38d90de:11)
> 	at com.android.builder.dexing.D8DexArchiveBuilder.convert(D8DexArchiveBuilder.java:120)
> 	... 32 more
> Caused by: java.lang.NullPointerException: Cannot invoke "String.length()" because "<parameter1>" is null
> ```
> 
> ```
> Caused by: com.android.tools.r8.CompilationFailedException: Compilation failed to complete, origin: ~/jetified-slf4j-simple-2.0.16.jar:org/slf4j/simple/OutputChoice$OutputChoiceType.class
> 	at Version.fakeStackEntry(Version_4.0.48.java:0)
> 	at com.android.tools.r8.internal.vk.a(R8_4.0.48_320a4fe2564c68ad8fe4492fea65872bc8f51e21c4d46e3dbac43afcc38d90de:75)
> 	at com.android.tools.r8.internal.vk.a(R8_4.0.48_320a4fe2564c68ad8fe4492fea65872bc8f51e21c4d46e3dbac43afcc38d90de:28)
> 	at com.android.tools.r8.internal.vk.a(R8_4.0.48_320a4fe2564c68ad8fe4492fea65872bc8f51e21c4d46e3dbac43afcc38d90de:27)
> 	at com.android.tools.r8.internal.vk.b(R8_4.0.48_320a4fe2564c68ad8fe4492fea65872bc8f51e21c4d46e3dbac43afcc38d90de:2)
> 	at com.android.tools.r8.D8.run(R8_4.0.48_320a4fe2564c68ad8fe4492fea65872bc8f51e21c4d46e3dbac43afcc38d90de:11)
> 	at com.android.builder.dexing.D8DexArchiveBuilder.convert(D8DexArchiveBuilder.java:120)
> 	... 38 more
> Caused by: java.lang.NullPointerException: Cannot invoke "String.length()" because "<parameter1>" is null
> ```

Same here.

**Comment by user-fal** [comment]
Hi,
Faced to the same issue. Does someone resolve it?

**Comment by vitalyster** [comment]
@user-fal see https://github.com/qos-ch/slf4j/issues/401#issuecomment-2362477992 - exclude `slf4j-simple` package

**Comment by user-fal** [comment]
Hi,

Finally resolving by update Gradle from 7.5 to 8.4 and gradle plugin from 7.4.2 to 8.3.0.
